version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: fm-postgres
    environment:
      POSTGRES_DB: financial_db
      POSTGRES_USER: fm_user
      POSTGRES_PASSWORD: fm_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: fm-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financial_db
      SPRING_DATASOURCE_USERNAME: fm_user
      SPRING_DATASOURCE_PASSWORD: fm_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  pgdata:
