version: '3.8'

services:
  transacoes-db:
    image: postgres:16-alpine
    container_name: transacoes-db
    environment:
      POSTGRES_DB: transacoes_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata-transacoes:/var/lib/postgresql/data
    networks:
      - rede-sistema

  transacoes-api:
    build: .
  #  build: ./transacoes
    container_name: transacoes-api
    depends_on:
      - transacoes-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transacoes-db:5432/transacoes_db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    networks:
      - rede-sistema

volumes:
  pgdata-transacoes:

networks:
  rede-sistema:
    external: true