version: '3.8'

services:
  transacoes-db:
    image: postgres:16-alpine
    container_name: transacoes-db
    environment:
      POSTGRES_DB: transacoes_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata-transacoes:/var/lib/postgresql/data
    networks:
      - rede-sistema

  # --- Mensageria ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rede-sistema

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - rede-sistema

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-setup
    depends_on:
      - kafka
    networks:
      - rede-sistema
    command: >
      bash -c "
      echo 'Aguardando o Kafka subir...'
      cub kafka-ready -b kafka:29092 1 30 && \
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic TRANSACAO-TOPIC && \
      echo 'TÃ³pico criado com sucesso!'"


  transacoes-api:
    build: .
    container_name: transacoes-api
    depends_on:
      - transacoes-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transacoes-db:5432/transacoes_db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    networks:
      - rede-sistema

volumes:
  pgdata-transacoes:

networks:
  rede-sistema:
    external: true